Tuesday September 3rd 2013 7:07 pm -04:00,The link Adrian posted below should clear it up specifically the section titled Calling functions within other function calls... read it very closely         , Resolved,0
Tuesday September 3rd 2013 7:12 pm -04:00,I misunderstood the deadline for week 2s exercise. What are the consequences of submitting late?, Resolved,0
Thursday September 19th 2013 4:36 pm -04:00,Method Description:Have you tested your function on the example in the handout?Message:ERROR: UnboundLocalErrorlocal variable get_complementary_sequence referenced before assignmentThis says to me that I am using g_c_s before I have defined it? I dunno.. I have cross-referenced what I have with what people seem to be using round here and it seems ok. , Unresolved,0
Thursday September 19th 2013 4:39 pm -04:00,And this is what comes up in IDLE. Traceback (most recent call last):  File <pyshell#8> line 1 in <module>    get_complementary_sequence(TA)  File <pyshell#7> line 11 in get_complementary_sequence    get_complementary_sequence = get_complementary_sequence + get_complement(dna)UnboundLocalError: local variable get_complementary_sequence referenced before assignmentIt makes sense in my head..!, Unresolved,0
Saturday September 21st 2013 7:59 am -04:00,I corrected my code using the advice you gave me (watched the vid on accumulators again). Now I have 22/24  instead of 21.. Ive spent so many hours on this one function and am getting nowhere. Method Description:Have you tested your function on the example in the handout?Message:FAILURE: AssertionError != TA+ TA : Have you tested your function on the example in the handout?Method Description:Have you tested your function on a sequence with multiple occurrences        of each nucleotide?Message:FAILURE: AssertionError != TAGCTAGC+ TAGCTAGC : Have you tested your function on a sequence with multiple occurrences            of each nucleotide?From browsing the forums and looking at the advice given by TAs and other users I cant get what Im doing differently., Unresolved,2
Saturday September 21st 2013 12:24 pm -04:00,The code I have for this Q (What is the sum of the even numbers from 524 through 10508 inclusive?) works in the python tutor visualizer tool on smaller numbers. If I try and do it with the numbers provided it stops at 299 and tells me it is avoiding a potential infinite loop. I try it in idle but it wont work at all the exact same code. I have tried it a dozen ways but get a different error every time even though I have the python tool set to the same python I am using (3.3)I sometime get SyntaxError: invalid syntaxother timesSyntaxError: multiple statements found while compiling a single statementand thenSyntaxError: unindent does not match any outer indentation levelSo even though my code works (I think..) I cant get the answer., Unresolved,0
Saturday September 21st 2013 1:42 pm -04:00,Thanks for taking the time to write all that out Claus. However my code works with smaller numbers the issue I am having is not that I cant get it to work but that the visualizer stops about 10% of the way through the calculation and I keep getting errors in the shell.My code was different to the way you advise. I just did the range the numbers and the step (2) then sum (0) + the result of the range. Dont want to print the whole thing b/c of honour code (I think people have posted pretty much the same code anyway though) but it works with say numbers between 127 and 200. But between 524 and 10805 (or whatever) it is too much to compute., Unresolved,0
Sunday September 22nd 2013 8:54 am -04:00,Hey Claus Im new to this obviously (why Im doing the course) but surely using the range method with a step of two starting on an even number will always produce a sequence of even numbers likewise starting on an odd number with a step of 2 will always produce a sequence of odd numbers? Thank you for taking the time to make two well considered posts though. I go up this morning and had another go in idle and had no syntax errors this time and consider the issue resolved., Unresolved,0
Saturday September 21st 2013 3:00 pm -04:00,Does it work for you in the visualizer? http://pythontutor.com/visualize.html#mode=displayIt must be something to do with the way I am entering it into idle considering those syntax errors. Well thanks for checking. The main thing is that I got the problem rather than the marks.. Ill just have to get the answers a different way! Cheers., Unresolved,0
Sunday September 22nd 2013 8:55 am -04:00,I figured that would be the case and tried typing it out moving the print line around etc and couldnt work so decided to come back in the morning and it works fine now. Sometimes I start getting errors for everything if I have typed too much crap into idle no matter what. Hmm. Well thanks for the help guys and I am sorry for wasting your time!, Unresolved,0
