Friday September 20th 2013 8:34 pm -04:00,Hi im having serious problems with get_complementary_sequence my get_complement function works fine but for some reason I cannot get it to work in my get_complementary_sequence. here is my code def get_complementary_sequence(dna):      >>> get_complementary_sequence(AT)    	(TA)    	>>> get_complementary_sequence(GC)   	(CG)       	sequence =    	for char in dna:       		complement = get_complement(dna)      		sequence = sequence + complement        	return sequenceplease help the error that keeps coming back in IDLE is  Traceback (most recent call last):  File <pyshell#0> line 1 in     get_complementary_sequence(AT)  File C:\Users\melody\Documents\Python programs\a2.py line 134 in get_complementary_sequence    sequence = sequence + complementTypeError: Cant convert NoneType object to str implicitlyI get why this error keeps on coming back but I dont know how to get the get_complement(dna) not to return the value None., Unresolved,0
