Thursday October 3rd 2013 6:50 pm -04:00,Hello I am able to open the text file (or so it says) but when I try to read it it tells me:Traceback (most recent call last):  File <pyshell#36> line 1 in <module>    file.read()AttributeError: str object has no attribute readIm using the sample text file given in the homework for now but I have tried other text files as well. Please advise thanks!!, Unresolved,0
