Wednesday August 21st 2013 3:30 pm -04:00,My compliments to the instructors! Ive taken several coursers courses and finished few. This is the most well organized with the clearest instructions and lectures by far! I am a college instructor and have been appalled by some other courses. This one I will get ideas from for my own online classes.My first is how great it is to have more and shorter lectures. So much easier to learn review and find things. Susan,None,5
Sunday September 1st 2013 2:49 pm -04:00,What does the new test case consist of?  And which module does it apply to?, Resolved,0
Friday September 13th 2013 11:57 am -04:00,Hi - I have a one line answer that works with every combination of inputs.  It has been marked wrong and I dont know what to do to challenge it.  Thanks., Resolved,0
Friday September 13th 2013 12:09 pm -04:00,all right I saw in another area that an extra set of parens will cause it to fail.  REALLY.  I use parens for clarification (and possibly those who might want to read my code later (I suspect this is something that would happen if you were a programmer....)  but if the grader is using regular expressions to parse the statement it will fail.....oh computers!  I will repost and hope for it to be marked correct., Resolved,0
Tuesday September 17th 2013 5:30 pm -04:00,If you look above I commented that I had the same problem.  I knew it worked both because it worked in IDLE but also because the logic was correct.  It turns out that the grading software barfs on too many parens ()when I reduced the parens by 1 set voila it worked.  Apropos of that I would say that you dont really need a set of parens around the second find statement because it is a single self-contained activity.  I personally thought that the second statement should all be included within parens for clarity but I dont think it is necessary.  So try reducing your parens in IDLE til correct and see if that helps get you through the test.  Good luck!, Resolved,0
Wednesday September 18th 2013 4:04 pm -04:00,In Q11 one of the possibilities is:, Unresolved,0
Wednesday September 18th 2013 4:13 pm -04:00,OOPS.  one of the possibilities is      a[1] = a[1][0]Where would I find an explanation of what the second notation means.  To me seeing a second index indicates dimensionality but that doesnt seem likely.  another OOPS.  I figured it out.  because in the previous step a string (AB) was put in the list you can use a subset to look at each element separately.....that is: a[1][0] = A and a[1][1 = B., Unresolved,0
Wednesday September 18th 2013 5:42 pm -04:00,yeah youre right too!  just a dimensionality I couldnt visualize until I put it through Visualizer... ;-}, Unresolved,0
Wednesday September 18th 2013 5:39 pm -04:00,I think if I had seen that first it would have made perfect sense.  It was that it was referring to a single list which if you think about is dimensional but I have mostly seen it when traversing tables...., Unresolved,0
Friday September 27th 2013 5:12 pm -04:00,I am just getting to this and submitted my is_valid_word.  Prior to submitting it I ran it with a number of different lists and words with success.  When I submitted it I got puzzling results:1. student: test_a3.Test_10_UpdateScore.test_01_return_type            returned SUCCESS  -- wasnt testing that!2. all of the tests related to test_a3.Test_03_IsValidWord.test_01_return_typereturned with the following:  my code is returning a bool so I dont understand (not a string not printing etc.)FAILURE: AssertionError<class NoneType> != <class bool> : Expected a <code>bool</code> to be returned., Unresolved,0
Friday September 27th 2013 6:25 pm -04:00,yes.  it sets found = False at the start and only changes it when it gets a hit., Unresolved,0
Friday September 27th 2013 7:03 pm -04:00,I use  if word in wordlist and set found to True if is true, Unresolved,1
Saturday September 28th 2013 10:38 am -04:00,Tom - I get exactly the same set of errors.  Shoot me now please -- I mean really ;-} This is such a simple set of instructions.  I have checked the file over to see if there might be something else creating problems.  I know that Python is finicky.  It would help me to know what the test harness is checking for so I could go backwards.  I have written code for make_string_from_row and it fails as well.  It also works in VISUALIZER.  I am quite certain that I am not making any of the common errors I see in other threads (like returning a string instead of Bool or trying to open the file in the code etc.)   IT has to be me because it is working for others but I think it must be something other than the code....and I cant find it., Unresolved,0
Saturday September 28th 2013 10:53 am -04:00,Tom -- what would cause the routine (structured as you suggested as a one-liner) to return None?  And to not reveal that to me.  I ask this because another error I get is         None != False  Wrong result returnedIn class if None is returned you see it on the line after the routine is run.  I NEVER see None., Unresolved,0
Friday September 27th 2013 8:18 pm -04:00,well actually I have a variable -- found -- which is initialized to False and which is returned regardless of its value.In testing the module in the Python shell the routine works properly.  I call it with a word which is not in the list and the routine returns False.  I call it with a word which is contained in the list and it returns True.   If I call it with a  string it returns False.  It is really a mystery to me that it is failing during the submission.  I have not had many problemswith my submissions -- I could generally figure out what was wrong so I didnt have to try to interpret the informationreturned after submission.  I dont know what test cases are tried; I dont really understand the error conditions; ANDI dont really know where to go and look to try to understand the submission report...., Unresolved,0
Friday September 27th 2013 9:48 pm -04:00,Method Description:NoneMessage:FAILURE: AssertionErrorNone != False : Wrong result returned. Consider what happens with the words BEEP and BEEPS., Unresolved,0
Friday September 27th 2013 9:56 pm -04:00,student: test_a3.Test_03_IsValidWord.test_04_subset_wordThis is one of the tests and the Failure notice above.  After reading it I tested BEEP and BEEPS with a result of False (not a string).I also ran it under visualize and it looks alright.  It is my understanding that an AssertionStatement is a statement of fact made by the test code.   I take it to mean that the test softwarethinks that I am returning None.  I was looking for it in visualize but dont see it.  the code is fairly straightforward -- setting a variable to False and changing it to Trueshould the word be in the list.  , Unresolved,0
Saturday September 28th 2013 10:15 am -04:00,Lillian - I have not been able to get it to work.  I truly believe there is something wrong with the autograder.  I think I am going to start a new thread with a shout out to get a TA to look at this problem.    Do you also get a SUCCESS onstudent: test_a3.Test_10_UpdateScore.test_01_return_typeI have written other code but that certainly isnt one of them....., Unresolved,0
Saturday September 28th 2013 10:06 am -04:00,Nick - thanks.  It occurred to me last night.  But VISUALIZER tells me that the code IS returning False or True.  I am truly baffled.    There is so little here ...how do I get the TAs on the line!?!?  oh and BEEP and BEEPS both return False., Unresolved,0
Saturday September 28th 2013 10:17 am -04:00,Oh and if  I do this:>>> print(is_valid_word(word_list BEEP))Falsedoesnt that mean it really is returning False????, Unresolved,0
Saturday September 28th 2013 2:08 pm -04:00,Here is code for is_valid_word:  return (word in wordlist)   sorry honor code -- but hey it apparently doesnt work anyways....I deleted the working file and downloaded a3.py again and inserted ONLY the above line.It works.  Someone else requested that I put it in an if statement which I did for both True and Falsestatements.  Only including the True statement -- but a False statement prints problemas follows:if is_valid_word([ANT BOX SOB TO] TO) == True:    print(s valid_word seems okay)else:    print(problem)s valid_word seems okayI also rebooted my computer.  I started a new thread requesting TA help.  Dont know if they will respond.  I think I am going to go on coding other subroutines because nothing I do seems to work in the test harness.  (I originally coded is_valid_word and make_string_from_row -- both which worked in VISUALIZER so that I could see that a bool was being returned for is_valid_word and a new string from make_string_from_row.....I truly appreciate all the suggestions.  But the above line of code has a return statement.  , Unresolved,0
Saturday September 28th 2013 11:44 am -04:00,OKAY.  So I decided to start anew.  I did the following:  1. deleted existing file code. 2.downloaded a new version of a3.py.  3. Made no changes.  4. Submitted code as downloaded.  RESULTS:  1/37.I succeeded in         student: test_a3.Test_10_UpdateScore.test_01_return_typeI have 2 errors:        test_a3.Test_01_ReadWords.test_02_one_line_file      AND                                 test_a3.Test_01_ReadWords.test_03_multi_line_file I then added a single line in is_valid_word  returning the evaluation of a word in the wordlist.I still have the SUCCESS listed above.  AND the same 2 errors.  I DO NOT have any ERRORS from the tests for is_valid_word just FAILURE.  I compared the failures in the completely EMPTY code submission report with the submission report from the code with what appears to be working code and the FAILURESARE IDENTICAL. It is as though the code I have written is not evaluated.BTW before I did this I closed everything and rebooted my machine.  Seriously I get 1 Success and 2 Errors without doing anything?  Any thoughts?, Unresolved,0
Saturday September 28th 2013 1:52 pm -04:00,Here are the results of what you asked..... if is_valid_word([ANT BOX SOB TO] TO) == True:	print(s valid_word seems okay)else:	print(problem)	s valid_word seems okay>>> if is_valid_word([ANT BOX SOB TO] BEEP) == True:	print(s valid_word seems okay)else:	print(problem)	problem, Unresolved,0
Saturday September 28th 2013 2:16 pm -04:00,Yeah that is what I originally submitted ...AND yes I am cursed! Good to see it works for someone else.  I actually simplified it to    return (word in wordlist)which should work as well -- just re-factoring.  I even tried it without parens because python doesnt like too much of anything and it too works but the test software tells me know.  , Unresolved,0
Saturday September 28th 2013 2:20 pm -04:00,Lillian - so happy to see it is working for you.  Im going to move on because I truly believe my code is correct and that something is messing up my test submission.  gremlins perhaps.   My original code was like yours and I simplified it to one line just a return (word in wordlist)I hope to find out sometime why this isnt being accepted but I  will instead try to get the game to work and worry about testing later...., Unresolved,0
Saturday September 28th 2013 2:49 pm -04:00,OKAY!  SUCCESS!  deleted everything and created an entirely new file -- no download. and only put the code for is_valid_word in.  Nothing changed logic-wise.  Clearly I introduced something I cant detect into a3.py which caused problems for the test harness.   THANK YOU thank you thank you for all the suggestions.  And not treating me like a blithering idiot!  I so appreciate it.  And Im glad I didnt give up although I felt like throwing the towel in a bit ago when there didnt seem to be any rhyme or reason.    In fact I will probably never know why it didnt work -- probably a failure of imagination on my part -- but when deleted // and redownloaded before and only added a single line of code  (which I truly believed was correct and have been proven it is )  and it still didnt work I thought I was bonkers., Unresolved,0
Saturday September 28th 2013 4:09 pm -04:00,No the goat didnt die in vain....LOL, Unresolved,0
Saturday September 28th 2013 2:30 pm -04:00,Id like to direct you to another thread  Need help interpreting failure in Summary from submission for is_valid_wordI have been having same problem with getting a positive test submission -- and there are a series of suggestions of how to look at your code.  If you dont find anything in that thread that helps AND you think that your code is correct will you please let me know?  People attempted the same code as I submitted and it worked for them.  I dont know why mine isnt.  Seriously please let me know what happens with your code. THANKS!, Resolved,1
Saturday September 28th 2013 2:57 pm -04:00,Hi Anon -- I am reposting what I just posted in the other thread because it finally worked for me.  I didnt change any code I just deleted all the files and created a new one with code for is_valid_word typed in by ME -- nothing else. read on...OKAY!  SUCCESS!  deleted everything and created an entirely new file -- no download. and only put the code for is_valid_word in.  Nothing changed logic-wise.  Clearly I introduced something I cant detect into a3.py which caused problems for the test harness.   THANK YOU thank you thank you for all the suggestions.  And not treating me like a blithering idiot!  I so appreciate it.  And Im glad I didnt give up although I felt like throwing the towel in a bit ago when there didnt seem to be any rhyme or reason.    In fact I will probably never know why it didnt work -- probably a failure of imagination on my part -- but when deleted // and redownloaded before and only added a single line of code  (which I truly believed was correct and have been proven it is )  and it still didnt work I thought I was bonkers.good luck.  There are some excellent suggestions of things to try in the other thread which if they work will convince you that you arent crazy or put you in the way of determining what might be wrong. , Resolved,0
Saturday September 28th 2013 11:49 am -04:00,I started a thread Need Help interpreting failure.  People have made lots of good suggestions but I still dont see what my failure is.OKAY.  So I decided to start anew.  I did the following:  1. deleted existing code. 2.downloaded a new version of a3.py.  3. Made no changes.  4. Submitted code as downloaded.  RESULTS:  1/37.I succeeded in         student: test_a3.Test_10_UpdateScore.test_01_return_typeI have 2 errors:        test_a3.Test_01_ReadWords.test_02_one_line_file      AND                                 test_a3.Test_01_ReadWords.test_03_multi_line_file I then added a single line in is_valid_word  returning the evaluation of a word in the wordlist and received the same 1/37.I still have the SUCCESS listed above.  AND the same 2 errors.  I DO NOT have any ERRORS from the tests for is_valid_word just FAILURE.  I compared the failures in the completely EMPTY code submission report with the submission report from the code with what appears to be working code and the FAILURESARE IDENTICAL. It is as though the code I have written is not evaluated.BTW before I did this I closed everything and rebooted my machine.  Seriously I get 1 Success and 2 Errors without doing anything?If you refer to the aforementioned thread you will see all the suggestions etc.  This is a single line of code:return (word in wordlist)  sorry honor code.  Works in visualizer and shell.  I am at a loss.  , Unresolved,0
Saturday September 28th 2013 2:50 pm -04:00,OKAY!  SUCCESS!  deleted everything and created an entirely new file -- no download. and only put the code for is_valid_word in.  Nothing changed logic-wise.  Clearly I introduced something I cant detect into a3.py which caused problems for the test harness.   THANK YOU thank you thank you for all the suggestions.  And not treating me like a blithering idiot!  I so appreciate it.  And Im glad I didnt give up although I felt like throwing the towel in a bit ago when there didnt seem to be any rhyme or reason.    In fact I will probably never know why it didnt work -- probably a failure of imagination on my part -- but when deleted // and redownloaded before and only added a single line of code  (which I truly believed was correct and have been proven it is )  and it still didnt work I thought I was bonkers., Unresolved,0
