Monday August 19th 2013 6:25 am -04:00,Somehow for each of the ord options offered in the question(0123) i got :Traceback (most recent call last):  File <pyshell#40> line 1 in <module>    ord(3)TypeError: ord() expected string of length 1 but int foundin IDLE. I was wondering why.Thank you, Resolved,0
Monday August 19th 2013 2:01 pm -04:00,Thank you this makes sense., Resolved,0
